### ISSUE TITLE
Supported runtimes in fn help init are out of date

### ISSUE THREAD

**Issue by tteggel** [fnproject/cli#104]
Actual:
```
fn help init
...
   --runtime value           choose an existing runtime - .go, .rb, .php, .rs, .js, .py, .cs, .fs, .java
...
```
Expected:
List of runtimes from https://github.com/fnproject/cli/blob/master/langs/base.go#L17

**Comment by denismakogon** [comment]
Would be nice to have CLI command to list runtimes

**Comment by treeder** [comment]
should get the help output from the list in base.go.

**Comment by treeder** [comment]
Fixed.
