### ISSUE TITLE
Generate FDK boilerplate for python 

### ISSUE THREAD

**Issue by zootalures** [fnproject/cli#111]
The CLI should generate boilerplate with a basic example on fn init (as per java) for go and python. 

* Should honor "FDK_VERSION" env option (or CLI option) to select FDK version explicitly 
* Should get latest version remotely and fix this in the func.yaml/code if not set
* Should include a basic "hello world" example
* Should include a fn test

**Comment by denismakogon** [comment]
So, the python thing is a bit tricky, since fdk-python doesn't support Py2 and does not support default format, we need two different boilerplates depending on the python version and format.

**Comment by delabassee** [comment]
Should the boilerplate also address the language specific runtime detection (i.e. when there's a source file already present). Right now it's very barebone (https://github.com/fnproject/cli/blob/6627438abb21eccf1e534e0f4b477fac09ffb046/init.go#L289) but other than for demo purpose, I'm not sure how useful this is.

**Comment by treeder** [comment]
@denismakogon how about just default to latest version of python in boilerplate. If they want to use older python, they can write their own function.

**Comment by denismakogon** [comment]
@treeder, sure thing. I’m more than happy to stick with python3 as default one

**Comment by carimura** [comment]
bump. can we agree on something and get this into CLI? it's a gap right now. thanks.

**Comment by denismakogon** [comment]
I’d say, let’s get rid of python2 and just have runtime: python3

For the boilerplate, let’s stick with json format and FDK-python.
