### ISSUE TITLE
--runtime help information confused

### ISSUE THREAD

**Issue by stevensu1977** [fnproject/cli#112]
--runtime help list file extend name like ".go",".java", is not runtime correct name,
other thing help information have no version information , like "python2.7", "python3.6", "node" ,"lambda-node-4" , it's not friendly useful .

may be we can use registry model, let  every XXXLangHelper reg self with runtime name

**Comment by carimura** [comment]
Thanks and agreed. I'll take a look at this one.

for reference:
` --runtime value           choose an existing runtime - .js, .py, .rs, .cs, .fs, .go, .rb, .php, .java`

and

```
~/workspace/hello
❯ fn init --runtime .go
Runtime: .go
Init does not support the .go runtime, you'll have to create your own Dockerfile for this functionERROR: could not detect entrypoint or cmd for .go, use --entrypoint and/or --cmd to set them explicitly

~/workspace/hello
❯ fn init --runtime go
Runtime: go
Function boilerplate generated.
func.yaml created.
```
