### ISSUE TITLE
Make binaries smaller

### ISSUE THREAD

**Issue by denismakogon** [fnproject/cli#114]
Use improved build command to reduce binary size:
```go
go build -ldflags "-s -w"
```
For each platform binary size goes down for at least 3-5 megs

**Comment by AstromechZA** [comment]
@denismakogon what is gained by reducing the file size by removing debugging symbols? It can make panics/stack traces much harder to work with and means one can't do cpu/allocation profiling in production.

**Comment by treeder** [comment]
Ya, I don't think there's much benefit here. Closing.
