### ISSUE TITLE
fn start doesn't support fnserver configuration options

### ISSUE THREAD

**Issue by denismakogon** [fnproject/cli#122]
We'd like to have DB, MQ, LogStore, etc. env vars configurable during `fn start`. Since Fn CLI uses exec, it's worth adding env file which is simple and requires less code to be changed.

**Comment by rdallman** [comment]
yea, this might be a good idea. on the other hand, i do think we were actively trying to discourage using `fn start` for any kind of complex deploy / testing (there are obvious issues with logs, signal handling, proc handling)

**Comment by denismakogon** [comment]
I do agree, that start cmd is just suppose to be simple thing to start with, so having an ability to set for instance datastore that is different from SQLite or different mq bring less complexity to run fn server. But, yeah, it’s must stay simple and not be something that meant to be for production, just local thing.
