### ISSUE TITLE
Broken "test" command

### ISSUE THREAD

**Issue by denismakogon** [fnproject/cli#133]
`fn test` doesn't set `FN_DEADLINE` which is required by FDKs (Go, Python).

**Comment by treeder** [comment]
When was FN_DEADLINE added and what is it for?  I don't see it documented anywhere.

**Comment by denismakogon** [comment]
FN_DEADLINE defines when function will timeout, each FDK implements deadline-based requests handler, so each function that uses FDK will fail without FN_DEADLINE.

Well, it’s not documented because developers don’t have an access to that.

**Comment by rdallman** [comment]
@denismakogon they do have access to it, we should doc it. fdk's just handle it nicely

**Comment by denismakogon** [comment]
Well, if they use FDK they have nothing to do with that because it’s already applied to their code. Indeed, worth documenting.

**Comment by skinowski** [comment]
I'll document this.
