### ISSUE TITLE
Docs to set content-type needs updating. 

### ISSUE THREAD

**Issue by carimura** [fnproject/cli#145]
```
❯ fn deploy --local --app ca
ERROR: yaml: unmarshal errors:
  line 5: cannot unmarshal !!str `applica...` into []string
```

**Comment by carimura** [comment]
this works:
```
headers:
  Content-Type:
  - text/html
```

this also works
```
headers:
  Content-Type: ["text/html"]
```

**Comment by rdallman** [comment]
those work as in they fix the issue or those work as in they reproduce the error you posted ?

**Comment by carimura** [comment]
sorry i forgot to include what doesn't work.. my bad :) 

does NOT work: 
```
headers:
  Content-Type: text/html
```

**Comment by carimura** [comment]
ok there.. updated comment above to clear up ambiguity

**Comment by treeder** [comment]
Can we close this?  What's the issue now?

**Comment by treeder** [comment]
Oh, docs need updating, changing title of this issue.

**Comment by rdallman** [comment]
done https://github.com/fnproject/fn/pull/711 -- edit in GH is nice
