### ISSUE TITLE
node build ignores package.lock & doesn't work with vendored deps 

### ISSUE THREAD

**Issue by zootalures** [fnproject/cli#153]
The node runtime build copies over package.json but not package.lock to the build dir before running `npm install`  - this nixes any package locks on the project and gives you unpredictable builds. 

also npm install  should be skipped if node_modules is already present in the build.

Expected behaviour:

* If node_modules is present, skip `npm install` completely 
* if package.lock is present, copy it alongside package.json before running `npm install`

**Comment by nishalad95** [comment]
I believe this is fixed in https://github.com/fnproject/cli/pull/171, can we close this issue?

**Comment by zootalures** [comment]
yep, fixed,
