### ISSUE TITLE
use same code as fn to execute docker containers

### ISSUE THREAD

**Issue by rdallman** [fnproject/cli#156]
right now we're using the docker cli, we should probably use the agent code from fn but it becomes something of an import issue. we used to extract just the driver and we could do that again, but there is a lot of machinery around hot functions that may need scoping to see what we need from there. since `fn run` really is only one invocation, we probably mostly just need the driver and possibly the dispatch code, maybe some other bits.

https://github.com/fnproject/fn/issues/241

**Comment by denismakogon** [comment]
related to https://github.com/fnproject/fdk-python/issues/36, for some reason, CLI keep sending the `\n` between the requests, but the agent doesn't. So it makes FDK-python for the local mode of the `fn test` and `fn run`.

**Comment by zootalures** [comment]
Closing as we don't do fn run any more
