### ISSUE TITLE
fn run access to func+app configs

### ISSUE THREAD

**Issue by carimura** [fnproject/cli#161]
does it make sense to have `fn run` get function configs? `fn run` is super nice for local development, but all funcs will almost inevitably use config secrets (ie db creds, etc.) which makes `run` unusable unless you write a script to set local env variables every time.... the alternative is to keep doing `fn deploy; fn call` but defeats entire purpose. Would be great to just map the funcs config into the ENV beforehand? That said we'd also need the app config as well.

ideally local development would have it's own set of dev creds for everything that the user controls, and prod is different, obviously.

**Comment by carimura** [comment]
this is what I'm trying to avoid:

`cat payload.json | fn run -e HOSTNAME=$HOSTNAME -e PUBNUB_SUBSCRIBE_KEY=$PUBNUB_SUBSCRIBE_KEY -e PUBNUB_PUBLISH_KEY=$PUBNUB_PUBLISH_KEY -e FUNC_SERVER_URL=$FUNC_SERVER_URL -e ANOTHER=$ANOTHER`

**Comment by carimura** [comment]
once we make progress on #211 (functions spec), `fn run` would know which ENV vars are required, and grab them from the users local ENV and pass them through to Docker using -e. Then I wouldn't need these annoying [runlocal.sh](https://github.com/carimura/vista/blob/master/services/detect-plates/runlocal.sh) scripts just to pass 5 ENV variables through every time I test locally.

**Comment by carimura** [comment]
also related: #20

**Comment by treeder** [comment]
If you use the `expects` stuff in func.yaml, it will automatically add them from your env.

**Comment by treeder** [comment]
And from your comment, it sounds like that would solve your problem.

**Comment by carimura** [comment]
I LOVE THIS!!
