### ISSUE TITLE
Issue 163 "--net host" breaks fn cli/fnserver communication

### ISSUE THREAD

**Issue by shaunsmith** [fnproject/cli#166]
RE: https://github.com/fnproject/cli/pull/163 

@rdallman @treeder  Fix for issue #163 has broken fnserver on Linux and Mac.  
fn cli is unable to connect to fnserver on 8080.  Yesterday @Nigel Deakin’s prometheus/grafana example wouldn’t run due to the use of `docker run` with `--link` and it complained about incompatibility with host networking.  We fixed that with https://github.com/fnproject/fn/pull/766.

This is a showstopper.  The only solution is to run fnserver directly as a container minus the “--net host”.

**Comment by rdallman** [comment]
i think it just breaks anything using `--link`, it doesn't break in the default case. `fn start` is not intended to be for complex `fn` installs, such as running an `fn` with extensions. A quick solution seems to be just add a flag to turn this off from `fn start`, for the default case i think we should keep it, but ultimately I don't think `fn start` is intended to work for most installs and we shouldn't cater it to every need (maybe we need a nicer way to discourage use?)
