### ISSUE TITLE
Runtime `python` should work

### ISSUE THREAD

**Issue by treeder** [fnproject/cli#204]
ie: `fn init --runtime python pfunc` doesn't work, but it should. 

And instead of `python3.6`, can we just make that `python3`?

**Comment by denismakogon** [comment]
I’m not sure that is the case. How would I know if the runtime is 3.6 but not 3.4? Code for 3.6 is not compatible with 3.4

Moreover, we use base image that is python:3.6, that’s why the runtime is also 3.6

**Comment by treeder** [comment]
Oh, I didn't realize Python had so many incompatibilities. What if we responded with something more helpful then?  ie: if you run `fn init --runtime python`, it will print a message with the available options.

**Comment by denismakogon** [comment]
I made the PR that adds back python alias, it’s not a big deal.

**Comment by rdallman** [comment]
this is done
