### ISSUE TITLE
As an Fn user I want to define multiple deployment contexts and be able to easily switch between them.

### ISSUE THREAD

**Issue by rikgibson** [fnproject/cli#217]
### Summary
A user should be able to use a local dev environment, or **Context**, for development and then be able to easily switch to a different context, e.g. dev/test/prod for deployment, such that any CLI commands that call an Fn Server API will be routed to the server pointed to by currently selected context, and configured with any required AuthN/AuthZ characteristics. Users should be able to create multiple contexts representing different deployment environments, with each context specifying an appropriate **Provider** to use and a set of properties required/understood by that Provider.

### CLI enhancements
- Create one or more remote deployment contexts:
  * `fn create context dev`
  * `fn create context test --key provider --value default`
- Populate the new context with a set of context-specific properties, e.g. type of cloud provider, Fn Server URL, target container registry and one or more cloud-provider specific properties, e.g.
  * `fn update context dev --key fn-api-url --value test.acme.com`
- List available contexts, showing all available contexts along with which is currently selected for use.
  * `fn list contexts`
- Switch to use a different context:
  * `fn use context test`
- The current context can be overridden on any CLI command using `--context=some-context`
  * `fn --context=test call myApp /hello`

### Contexts
Contexts are persisted in individual files underneath an Fn-specific directory, for example:

`~`
`  .fn`
`    config.yml`
`    contexts`
`      local.yml`
`      dev.yml`

The `config.yml` will contain the name of the currently selected context:

`- current-context : local`

The CLI will load the `config.yml` on launch and parse to determine the currently selected context, which will then also be loaded.  If the `.fn` directory or `config.yml` are not present, the CLI will create them and populate with simple default information.

### local.yml
`- context`
`    name : local`
`    provider : default`
`    fn-api-url : localhost`
`    registry : `

### Configuration Using Environment Variables
The current CLI implementation supports a couple of env vars - FN_API_URL and FN_REGISTRY.  These should be replaced by equivalent properties defined in contexts, however there are still use cases where the use of these variables is useful or preferable (CI testing for example). If the CLI detects both an env var and an equivalent context property, the env var will override the context property, with the CLI outputting a warning to this effect:

`Warning: environment variable FN_API_URL is overriding configured context property fn-api-url from context "local"`

### Providers
The effect of all of this is that when the CLI wants to make an outbound Fn API call, the context configuration bundle (including any env var overrides) should be passed into the Fn Go SDK such that it can be handed off to a relevant *Provider* to encode the outbound HTTP request accordingly.

### Default Provider
Whilst it is beyond the scope of this issue to start building provider implementations for third-party cloud vendors, an initial "default" provider will be created that will provide unauthenticated access to any free-standing Fn Server instance.

**Comment by zootalures** [comment]
> The  CLI will load the config.yml on launch and parse to determine the currently selected context, which will then also be loaded. If the .fn directory or config.yml are not present, the CLI will create them and populate with simple default information

does this mean that local could be updated?  (e.g. to be non-local) - could this be `default` ?

**Comment by rikgibson** [comment]
Some aspects of `local` (or `default`) should be immutable, e.g. an `fn-api-url=localhost` should be fixed as this [I think] is the only context for when `fn start [server]` should apply. However if we are following the logic that the use of contexts should supplant normal use of env-vars, an `fn-registry` property should still be mutable.

This brings into question what does `fn start [server]` do if using a non-local context? Does it still start a local server, or simply issue a message stating that a remote server can't be started or stopped?

It could be that `local.yml` doesn't actually exist as a .yml file, instead the local/default context could be implicit and only accessible using the CLI.

**Comment by carimura** [comment]
This is awesome. Seems to track k8s context methodology.

`local` could be the first auto-generated context with default values (ie fn-api-url=localhost:8080). Probably easiest just to treat the `local` context like any other context. mutable if desired.

I think the Minio client has a similar model of `local` and `play` available out of the box, the latter being a hosted playground. but can't remember exactly.

**Comment by treeder** [comment]
Love it. Couple comments:

* I don't think `create` and setting values should be part of the same command. 
* Since update requires key and value, could we skip the flags?  eg: `fn update context dev fn-api-url  test.acme.com`
* A step further, instead of specifying the context to set key/values on it, could it just use the current context, eg: `fn use dev` then `fn set fn-api-url test.acme.com`

**Comment by mantree** [comment]
We're getting into the implementation of this and having some doubts about the idea of modifying the context files via the cli. Essentially writing a cli update interface for local files seems a bit redundant.

Instead, we propose:

* Create a context configuration with a template specific to the supplied provider
    * fn context create <name> <provider>
* List available contexts, showing all available contexts highlighting currently selected for use.
   * fn context list
* Switch to use a different context:
   * fn context set test
* The current context can be overridden on any CLI command using --context=some-context
   * fn --context=test call myApp /hello

This introduces the concept of provider context templates, we're imagining the following:

```bash
$ fn context create dev oracle
Created context dev with oracle template

$ tree ~/.fn
.
├── contexts
│   ├── dev.yaml
├── config.yaml

$ cat ~/.fn/contexts/dev.yaml
provider: oracle
compartmentId: <COMPARTMENT ID>
region: <REGION>
keyId: <KEY ID>
```
Users can then complete the file, or perhaps download a setup file from the UI in due course. 

The example above are <noun> <verb> to fit with the current structure.

**Comment by rikgibson** [comment]
@mantree The key question here is what is the best experience for the user? Is it better to create a text file and then expect them to go and edit that file, or is it better to give them a simple interface for editing context properties?  I'm open to giving your proposal a try and gathering user feedback, but a couple of questions:

1) Where/how is the template for a provider defined? The CLI already has a bunch of problems with function boilerplate hardcoded inside the main source - the templates should be defined as text files alongside the provider code rather than in the code itself.

2) What about the local/default context? See point above by @carimura about `default` being auto-generated rather than being represented by an actual file on disk, yet still being mutable. This proposal would imply that the `default` context needs to exist as a real file, which might be fine.

**Comment by carimura** [comment]
We should consider matching the other adjacent tech CLI's... not blindly, but taking advantage of market familiarity and learnings they've gone through. For example: kubectl (configs/contexts have cli support), minio (config/hosts have cli support), docker (docker logins write to config file and have cli support), openwhisk (not sure?).

Having CLI support is consistent. Again I don't want to follow anything blindly but in this case, I think it makes sense.

**Comment by rikgibson** [comment]
Done.
