### ISSUE TITLE
`fn deploy` override "cpus" in func.yaml and other unknow settings

### ISSUE THREAD

**Issue by kuashe** [fnproject/cli#218]
Using the current func.yaml

```
version: 0.0.28
runtime: node
entrypoint: node func.js
format: json
cpus: 0.1
```

After running `fn deploy` my func.yaml looks like this

```
version: 0.0.28
runtime: node
entrypoint: node func.js
format: json
```

This is also true when using unknow settings , but for cpus it should be supported by the [CLI ](https://github.com/fnproject/fn/blob/master/docs/developers/function-file.md)

**Comment by denismakogon** [comment]
CLI does not support cpu as far as I know

**Comment by carimura** [comment]
@denismakogon https://medium.com/fnproject/introduction-to-fn-projects-function-limits-da6ee8d5f76f

**Comment by carimura** [comment]
Cc @skinowski

**Comment by skinowski** [comment]
I'll add this...

**Comment by skinowski** [comment]
#219 ready for review.

**Comment by kuashe** [comment]
Thanks @skinowski , tested on my mac works perfectly.
