### ISSUE TITLE
Confusing error when not Docker logged in

### ISSUE THREAD

**Issue by carimura** [fnproject/cli#222]
When doing `fn deploy` I get the following error if I'm not logged into my registry:

```
denied: requested access to the resource is denied
ERROR: deploy error on /go/src/github.com/carimura/myapp/buycar/func.yaml: error running docker push: exit status 1
```

Can we catch this error somehow and suggest a `docker login`?

**Comment by peterj** [comment]
There are multiple different ways to figure this out, but none of them are really complete and in each case you actually have to perform an action (e.g. docker pull/push) to see if the credentials are correct and user can be/is logged in.

The simplest way (definitely not the most elegant :)) in this case would be to check the error returned in [common.go](https://github.com/fnproject/cli/blob/master/common.go#L328).
