### ISSUE TITLE
As a developer I want to specify the content type in my test.json so that I can control the content type in my tests.

### ISSUE THREAD

**Issue by shaunsmith** [fnproject/cli#235]
See https://github.com/fnproject/cli/issues/234 for background on the need to specify content type on function invocation.

In a test.json, specification of the content type of the body should be supported by addition of a property to the top level test object.  Content type currently defaults to `application/json` so for backwards compatibility this default should remain in place.

JSON body example (contentType could be omitted):

```
{
    "contentType" : "application/json",
    "tests": [
        {
            "input": {
                "body": {
                    "name": "Johnny"
                }
            },
            "output": {
                "body": {
                    "message": "Hello Johnny"
                }
            }
        }
    ]
}
```

Text body example (must specify contentType):

```
{
    "contentType" : "text/plain",
    "tests": [
        {
            "input": {
                "body": "Johnny"
            },
            "output": {
                "body": "Hello Johnny"
            }
        }
    ]
}
```

**Comment by rikgibson** [comment]
As an addendum to this, it's worth looming at whether the "contentType" declaration could/should be at the test level, rather than at the top level.

**Comment by rdallman** [comment]
fn test is dead, huzzah
