### ISSUE TITLE
fn apps list broken

### ISSUE THREAD

**Issue by kaslin** [fnproject/cli#239]
Just installed fn & the fn cli.  When I run "fn apps list" I get the following error:
$ fn apps list
ERROR: Path not found: /apps

$ fn version
Client version:  0.4.73
Server version:  0.3.422

**Comment by denismakogon** [comment]
Can you post please more details:
1. Which OS?
2. What’s in FN_API_URL env var?
3. Was Fn able to start successfully? (Try `curl -v <fn-endpoint>:<fn-port>/v1/apps`)

**Comment by kaslin** [comment]
MacOS Sierra version 10.12.6 (is where the cli is installed)

Don't want to give my endpoint but:

curl -v $FN_API_URL/v1/apps
*   Trying xxx.xx.xx.xx...
* TCP_NODELAY set
* Connected to xxx.xx.xx.xx (xxx.xx.xx.xx) port 80 (#0)
> GET /v1/apps HTTP/1.1
> Host: xxx.xx.xx.xx
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 73
< Content-Type: application/json; charset=utf-8
< Date: Fri, 20 Apr 2018 22:05:58 GMT
< 
* Connection #0 to host xxx.xx.xx.xx left intact

**Comment by carimura** [comment]
confirmed this is happening for me also.... regression -- need fix and test asap

```
/private/tmp
❯ fn version
Client version:  0.4.73
Server version:  0.3.421

/private/tmp
❯ fn apps list
ERROR: Path not found: /apps
```

**Comment by rdallman** [comment]
weird, i can't repro this one

**Comment by rdallman** [comment]
built from source:

```
cli(master): ./cli version
Client version:  0.4.73
Server version:  0.3.422
cli(master): ./cli apps list
no apps found
```

**Comment by rdallman** [comment]
```
cli(master): echo $FN_APP_URL

cli(master):
```

could you paste yours? i expect this is it, mine is blank.

**Comment by carimura** [comment]
actually same bug both locally and on current api.fnservice.io service which was deployed last night.

```
❯ echo $FN_API_URL
http://localhost:8080
```

**Comment by rdallman** [comment]
mhmm, that's it:

```
cli(master): FN_API_URL=http://localhost:8080 ./cli apps list
ERROR: Path not found: /apps
cli(master): ./cli apps list          
no apps found
```

can fix shortly

**Comment by carimura** [comment]
thanks. whatever this is broke a bunch of commands -- not sure how it passed tests?

```
~/workspace/hello
❯ fn routes l myapp
ERROR: Path not found: /apps/myapp/routes
```
