### ISSUE TITLE
As a developer I want to be able to specify the content type for my function so that my function can correctly process the incoming payload

### ISSUE THREAD

**Issue by rikgibson** [fnproject/cli#246]
Currently there is no way for a function developer to specify the content-type for a function as part of the function definition, or as an option to `fn call` or `fn run` - the only option is to use `curl` to invoke a function and specify the Content-Type header in that. The CLI also currently appears to hardcode the Content-Type header to `application/json` (see call_fn.go:50) which causes problems in FDKs that want to use this header to determine whether or not to parse the request body before passing downstream to the function.

Both the current [Fn JSON format](https://github.com/fnproject/fn/blob/master/docs/developers/function-format.md#json-io-format) and the proposed [CloudEvent format](https://github.com/cloudevents/spec/blob/master/serialization.md#json) include the specification of content type.

See [Slack conversation](https://fnproject.slack.com/archives/C7FKW83GV/p1524084084000279?thread_ts=1524050601.000350&cid=C7FKW83GV) for the discussion that lead to this issue being filed. 

This issue proposes the following, individually tracked by three smaller issues:

- [X] **func.yaml** (#248)

We should extend the properties supported in `func.yaml` with an optional `content-type` property, which will default to `text/plain` if not otherwise specified. The CLI will respect this and set the Content-Type header in the HTTP request sent to the Fn API.

- [X] **Overriding in "fn call" and/or "fn run"** (#234)

`fn call` and `fn run` should have an additional `--content-type` option that allows the content type to be set directly from the CLI, overriding the value set in func.yaml (or defaulted). 

- [ ] **Specifying test content type in test/json** (#235)

In a test.json, specification of the content type of the body should be supported by addition of a property to the top level test object.  Content type currently defaults to `application/json` so for backwards compatibility this default should remain in place.

JSON body example (contentType could be omitted):

```
{
    "contentType" : "text/plain",
    "tests": [
    ...
```

**Comment by denismakogon** [comment]
I kind of disagree that content type should be global for all tests, it has to be specific for each one.

**Comment by rdallman** [comment]
`fn test` is dead, closing!
