### ISSUE TITLE
As a developer I want to be able to start an Fn Server on a port other than 8080 using "fn start" so that I don't have to resort to using "docker run"

### ISSUE THREAD

**Issue by rikgibson** [fnproject/cli#247]
This is a simple proposal of just adding a `--port -p` option to `fn start`, e.g.

`fn start --port 8081`

This (or lack of) came up several times during the recent Fn Scandinavia Roadshow - there are typically a couple of reasons that users may want to do this:

1) They already have existing services/processes running on port 8080.
2) They want to launch a second Fn Server process on the same box.

We could take this opportunity to add a symmetric `fn stop [--port]` as well, which would allow users to choose which server to stop when they have started more than one. The CLI Command Structure proposal (#216) includes such an extension if not done here.

**Comment by riconnon** [comment]
Is it sufficient to have `fn start --port` or would it be better to have something like `fn start --bind` which could accept `fn start --bind 8081` or `fn start --bind 192.0.2.1:8081`

The latter would allow binding the fn server to a specific interface/IP

Both are equally simple to implement really.
