### ISSUE TITLE
fn deploy should remove a config val when deleted from app.yaml/func.yaml

### ISSUE THREAD

**Issue by carimura** [fnproject/cli#251]
we've had this discussion before (/giphy bill murray groundhog day) -- if something is deleted from an app/func.yaml file, is the intention that it is also removed on `fn deploy`?

For example, create an app.yaml and give it 3 config vals, deploy the app, then remove 1 config val from the yaml, deploy again, all 3 will still exist on the service.

I think it needs to go away. that's the expected outcome.

**Comment by rdallman** [comment]
dupe of https://github.com/fnproject/fn/issues/803 that had discussion

**Comment by carimura** [comment]
right. i knew it was somewhere, thanks.
