### ISSUE TITLE
Eliminate default application/json as content type while doing "fn call"

### ISSUE THREAD

**Issue by denismakogon** [fnproject/cli#253]
Original issue: https://github.com/fnproject/fn/issues/964
Related: https://github.com/fnproject/fdk-go/issues/23

**Comment by rikgibson** [comment]
@denismakogon see #246 and related sub-issues. On our backlog, let me know if this needs prioritising sooner.

**Comment by denismakogon** [comment]
that's something needs to be done soon enough because it harms cloudevents experience at this moment.

**Comment by rikgibson** [comment]
OK, will get someone on it.

**Comment by rikgibson** [comment]
Closing - duplicate of #246.
