### ISSUE TITLE
As a developer I would like to run fn cli commands providing a target working directory

### ISSUE THREAD

**Issue by shaunsmith** [fnproject/cli#268]
To better support integration with CI/CD tools and platforms the fn cli should accept a command line option specifying the working directory a given command should execute in.  This support would avoid having to cd to `/a/path/to/my/app` to perform operations.  For example, using current command structure:

`fn build --dir /a/path/to/my/app --all`
`fn run --dir /a/path/to/my/func`
`fn deploy --dir /a/path/to/my/app --all`

Although I used `--dir` in the examples I don't have a strong opinion on the actual command switch name.

**Comment by JadeRedworth** [comment]
We have 2 options here:

1. To specifiy the `--dir` flag only on the commands we want (build, run, deploy..)
OR
2. Create a global flag `--dir` which can be accessed by all commands.

What do you think @shaunsmith ?

**Comment by shaunsmith** [comment]
I think only add `--dir` to commands where it makes sense.  It seems only a few really need it.  I guess I should have provided a list of commands with the enhancement request.  My only defence is that the command structure was going to change so it didn't make sense at the time. 😜

**Comment by shaunsmith** [comment]
@JadeRedworth I took a look a the current fn CLI commands and think `dir` support makes sense for:
- build -- builds the function in `dir`
- bump -- bumps the version in the func.yaml in `dir`
- deploy -- deploys function or app (if `--all` used) in `dir`
- init -- creates a function in `dir`, or in subdirectory of `dir` if function name provided
- run -- runs function in `dir`
- test -- tests function in `dir` using test.json in same folder

Your PR https://github.com/fnproject/cli/pull/309 doesn't handle all of these cases yet.
