### ISSUE TITLE
Improve config inspection

### ISSUE THREAD

**Issue by shaunsmith** [fnproject/cli#27]
`fn apps config` and `fn routes config` support both `set` and `unset` but lack `get` or `list`. 
 Currently the only way to find out a configuration value is to use `inspect` which returns a JSON document with more than just the user specified configuration key/value pairs.

I suggest  adding a `get` command to both apps and routes config command which would take the key name and return the associated value.  

```sh
$ fn apps config set myapp loglevel debug
myapp updated loglevel with debug
$ fn apps config get myapp loglevel
debug
```

For symmetry with other commands that have a `list` command we should also add `list` and `l` to both apps and routes config.  This would just return a list of key/value pairs in plain text, like `fn apps list`.  Not sure what the delimiter should be but if we used = then it would look like the following:

```sh
$ fn apps config set myapp loglevel debug
myapp updated loglevel with debug
$ fn apps config set myapp timeout 400
myapp updated timeout with 400
$ fn apps config list myapp
loglevel=debug
timeout=400
```

**Comment by tonto** [comment]
Can I take this one?

**Comment by carimura** [comment]
definitely!

**Comment by tonto** [comment]
@shaunsmith What should we output for routes get/list

**Comment by tonto** [comment]
path?

**Comment by carimura** [comment]
@tonto `fn routes get/list` already works. it's `fn config get/list` that the ticket is requesting.

**Comment by tonto** [comment]
um, why does the ticket say `suggest adding a get command to both apps and routes config command which would take the key name and return the associated value.`

**Comment by tonto** [comment]
It requests `apps config get/list` and `routes/config get/list` and nevermind the question, I answered it myself `routes/config is also map[string]string`

**Comment by carimura** [comment]
Oh misunderstood. Routes can also have configs, thought you were asking about routes command. Carry on.
