### ISSUE TITLE
As an application developer I would like to be able to stop a local Fn Server using the CLI so that I don't have to figure out the container to stop.

### ISSUE THREAD

**Issue by denismakogon** [fnproject/cli#270]
So, we have `fn start -d` which starts Fn server in detached/background state. If i have no idea how container named, how can i stop the Fn server?

**Comment by rikgibson** [comment]
Yes the stop experience isn't great. Obviously a quick `docker ps` yields the name of the container but a symmetric `fn stop` would be good. We need to think about how this fits in with the contexts enhancements that have come in, along with the `--port` option on `fn start` that @riconnon is about to deliver, but generally yes - point taken.
