### ISSUE TITLE
Management command help text is inconsistent/not useful

### ISSUE THREAD

**Issue by msgodf** [fnproject/cli#306]
The help text for the management commands could be a lot more helpful.

```
   MANAGEMENT COMMANDS:
     config, cf  set configuration for an object
     create, c   create
     delete, d   delete command
     get, g      get command
     inspect, i  inspect command
     list, ls    list command
     unset, un   unset command
     update, up  update command
     use, u      use command
```

`config` and `create` are inconsistent with the others, and the others don't give any suggestion as to how/why you would use them.

**Comment by rikgibson** [comment]
Yeah, aware of this but didn't want it to block the overall command delivery. I've also been talking to @michael-w-williams about getting him involved in helping with our text, also about externalising the help text to potentially enable generation of online CLI reference docs.
