### ISSUE TITLE
func.yaml "build:" should override the runtime docker-based build?

### ISSUE THREAD

**Issue by jan-g** [fnproject/cli#31]
Not sure if this is a bug or behaving as designed, but it's non-obvious:

I've a func.yaml that specifies a `build:` command sequence. Somewhat surprisingly, I'm seeing a build running twice - the mvn invocation (this instance is using the java runtime) runs locally (which works), then attempts to run a second time inside the scope of the dockerbuild (which in this case, will fail).

I can work around this by supplying a custom Dockerfile, but - is this intended behaviour?

(Incidentally it took a while to spot what was going on because the first mvn build was hidden by #5.)

**Comment by treeder** [comment]
That actually is intended before. The build commands are more pre-build commands, so you can build an artifact(s), then bundle it into a docker image. Now that multi-stage builds are out though, kind of obsoletes the usefulness of it. 

And yes, to do special builds, the idea is to BYOD (bring your own Dockerfile). 

Open to other ideas though.

**Comment by jan-g** [comment]
FWIW, the reason to want a "local" build stage is that many java functions may be maven child
modules - that refer to a parent module in a higher directory. However, on reflection it seems reasonable to expect a custom Dockerfile (in fact, to be using runtime=docker) for these.
