### ISSUE TITLE
How to make request to fn-server that require authenticated header?

### ISSUE THREAD

**Issue by andytruong** [fnproject/cli#311]
Hi there, I added a simple authentication for my fn-servers, but I am not sure how to manage these fn-server from fn-cli. Can we configure request headers to the `context`?

Thanks.

**Comment by zootalures** [comment]
Hey - great question! 

Currently the Fn CLI and go sdk only support bearer-tokens for the default provider out of the box  - 

Supporting basic auth sounds like a good idea  -  I think this should be in the default  providier (as an alternative to tokens. 

You should be able to do this by updating the default Provider: https://github.com/fnproject/fn_go/tree/master/provider/defaultprovider - e.g. by accepting new config parameters (user/password?) for basic auth as an alternative to token.

**Comment by zootalures** [comment]
I've put a basic idea together - would this work for you? 
https://github.com/fnproject/fn_go/pull/8

**Comment by andytruong** [comment]
Thank you @zootalures 

It's working by adding "token" to my context `.fn/contexts/NAME.yaml`.

I think we should update the context documentation  to mention this cool option.

**Comment by zootalures** [comment]
Awesome, glad it worked out, I’ll look at the docs asap
