### ISSUE TITLE
As an app developer I want to init a new function that includes an HTTP Trigger.

### ISSUE THREAD

**Issue by rikgibson** [fnproject/cli#324]
With the move to the new v2 API, where Routes are replaced with Functions and Triggers, the 'fn init' command along with the content of `func.yaml` need updating to meet the needs of the new model.

**func.yaml**
A `v1` file looks like this:

`name: myfunc`
`version: 0.0.1`
`runtime: java`
`cmd: com.example.fn.HelloFunction::handleRequest`
`build_image: fnproject/fn-java-fdk-build:jdk9-1.0.63`
`run_image: fnproject/fn-java-fdk:jdk9-1.0.63`
`format: http`

A `v2` file with an equivalent HTTP Trigger should look like this:

`name: myfunc`
`version: 0.0.1`
`runtime: java`
`cmd: com.example.fn.HelloFunction::handleRequest`
`build-image: fnproject/fn-java-fdk-build:jdk9-1.0.63`
`run-image: fnproject/fn-java-fdk:jdk9-1.0.63`
`triggers:`
`    - name: my-func-trigger:`
`      type: http`
`      source: /my-func`

A `v2` file without any Triggers should look like this:
`name: myfunc`
`version: 0.0.1`
`runtime: java`
`cmd: com.example.fn.HelloFunction::handleRequest`
`build-image: fnproject/fn-java-fdk-build:jdk9-1.0.63`
`run-image: fnproject/fn-java-fdk:jdk9-1.0.63`

**fn init**
With the `v1` API, `fn init my-func --runtime=java` creates a Route. In `v2`, Functions can exist with or without Triggers, so the `fn init` command needs a little more flexibility.

Initialising a new function that includes a Trigger should be done like so:

`fn init my-func --runtime=java --trigger=http`

and creating a Function without a Trigger would simply be:

`fn init my-func --runtime=java`

Alternatively, we could preserve (or mimic) existing behaviour whereby `fn init my-func --runtime=java` will auto-generate an HTTP Trigger, and a `--trigger=none` could then generate a function without a Trigger, but this seems a little clunky and forcing compatibility at the cost of clean syntax.

**Comment by mantree** [comment]
A couple of things not quite right here to my mind, specifically around 'version'. The new V2 fn entity doesn't have a distinct 'version' field, the value is bundled into the 'image' field.

This actually presents an opportunity to retrieve 'version' for it's more regular usage as an api version. Therefore a V2 fn definition would look like:

fn.yaml
```
version: 2
name: myfunc
runtime: java
cmd: com.example.fn.HelloFunction::handleRequest
build-image: fnproject/fn-java-fdk-build:jdk9-1.0.63
run-image: fnproject/fn-java-fdk:jdk9-1.0.63:1.0.0
triggers:
    my-trigger:
        type: http
        source: /my-trigger-path
```

We should also start calling these things 'fn.yaml' to match the terminology used in the service. That would also really help differentiate the versions of things.

**Comment by rikgibson** [comment]
`fn.yaml` is an interesting thought, and an easy v1 v v2 detection mechanism.  I also took the leap of removing "format", which is really where we need to go with the `cloud-event` only direction.

**Comment by rikgibson** [comment]
I also changed "_" to "-"...

**Comment by shaunsmith** [comment]
The `version` property is used by `fn build|deploy|push` to set the tag on the generated image.  I have no problem with distinguishing between image tag/version and file format/API version but don't we need both?

I like the idea of moving to fn.yaml as we embrace this new structure.

`format` should definitely be obliterated! ;)

**Comment by rikgibson** [comment]
`format` dying is a good thing but it does rather rely on having all the necessary cloud-event support in place first, which isn't very high up the priority list at this time. But that can be discussed.

**Comment by sachin-pikle** [comment]
May be a stupid question to ask here but what does a function with no triggers mean? Just a Docker image in the repo which will never get called?

**Comment by rikgibson** [comment]
A function without a trigger can still be invoked using a new "direct invoke" endpoint, something like http://localhost:8080/v2/invoke/<function-id>.
