### ISSUE TITLE
As an app developer I want to easily migrate my v1 functions to v2 functions so that I don't have to manually update all of my func.yaml files.

### ISSUE THREAD

**Issue by rikgibson** [fnproject/cli#325]
As the conceptual model changes from the Fn `v1` Routes-based API to the `v2` Functions+Triggers based API, this imposes certain changes on the `func.yaml` (see #324). The question arises how to deal with the transition from a `v1` `func.yaml` to a `v2` `func.yaml`.  There are broadly three options:

1) Internally maintain compatibility with a `v1` YAML, implicitly translating a Route into a Function+Trigger at `fn deploy` time, deprecating the `v1` format with a view to removing support at some future point in time.

2) Don't support `v1` YAML files, detect they are `v1` and emit a statement the function/yaml needs migrating to a `v2` format, and provide a `fn migrate` CLI command to update the YAML. Essentially this would rename `func.yaml` to `func.yaml.bak` and generate a new v2-compliant `func.yaml` per the format outlined in #324.

3) Similar to 2) but without the migration support - we detect the old version and just tell the developer to update the YAML, linking out to updated docs for help.

Initially we were thinking that 3) would suffice as the least work, but with an increasing developer base thanks to a lot of recent dev-rel work it would seem a better plan to lean towards 2), i.e. don't support v1 but do provide a simple migration tool/command.

**Comment by mantree** [comment]
2 seems the way forward to me.

A clean break with the older format, with a clear way of migrating made available.

**Comment by zootalures** [comment]
2

**Comment by riconnon** [comment]
2

**Comment by shaunsmith** [comment]
2

In #323 @mantree suggested renaming `func.yaml` to `fn.yaml` for v2 which as @rikgibson pointed out makes it easy to distinguish between v1 and v2 format files.   So with Option 2, the CLI could detect the missing `fn.yaml` and if a `func.yaml` were present offer migration assistance.

**Comment by zootalures** [comment]
In the case of 2 and with renaming we should start to assemble a list of where this has impact (docs, tests, tutorials, blogs ......)  .

**Comment by rikgibson** [comment]
`func.yaml` no longer being renamed to `fn.yaml` so 2) should be as defined above.

**Comment by saintarian** [comment]
My 2c - Adding an `fn migrate` command to the CLI for this seems like overkill. Are we supporting that command forever? Will it handle all other migration scenarios that will come up? 

Maybe better to throw an error in the CLI and point them to, say, a python script that does the fixup.

**Comment by rikgibson** [comment]
I don't think it's overkill - the goal here is create a smooth experience for the user when things do change, which they will again. I also don't think this is intended as a stop-gap, and if/when the `func.yaml` moves to v3, v4 and beyond we can continue to detect old versions and move them through to whatever the current version is by doing, for example v1 --> v2 --> v3 --> v4.

It's not a big piece of work, and the better UX over just outputting errors and asking folks to download scripts justifies the effort IMO.
