### ISSUE TITLE
add app syslog_url configuration support

### ISSUE THREAD

**Issue by rdallman** [fnproject/cli#362]
curl example: `curl -X PATCH -d '{"route":{"syslog_url":"tcp://myurl"}}' http://my.fn.com`

cli should be something along the lines of:

```
fn update app my-app --syslog_url=tcp://xys.papertrailapp.com:42
```

for any relevant verbs (update, create, others?).

the documentation for the feature is https://github.com/fnproject/fn/blob/master/docs/operating/logging.md#remote-syslog-for-functions and we should likely update it with a CLI command to set the field.

**Comment by sachin-pikle** [comment]
@rikgibson - Can we prioritize this one please? It's a blocker for Abhishek to export customer logs to paper trail.

**Comment by msgodf** [comment]
Should it be `--syslog_url` or `--syslog-url`?

**Comment by abhirockzz** [comment]
`syslog_url` - https://github.com/fnproject/fn_go/blob/master/models/app.go#L40

**Comment by JadeRedworth** [comment]
@msgodf `--syslog-url` is consistent with `--api-url` and value within a context file.

**Comment by josephholsten** [comment]
may this issue be closed?

**Comment by rdallman** [comment]
yep, ty
