### ISSUE TITLE
CLI init adds "testing" dependency instead of "testing-junit4"

### ISSUE THREAD

**Issue by wombstrat** [fnproject/cli#365]
When running `fn init --runtime java javafn`, the `<artifactId>testing</artifactId>`  is added by default instead of '<artifactId>testing-junit4</artifactId>'. 
The testing dependency doesn't contain the FnTestingRule class, which provokes a compile error.

**Comment by zootalures** [comment]
Please try latest CLI

**Comment by mjg123** [comment]
This was fixed with https://github.com/fnproject/cli/commit/60128b3211fa5305d206783e4d4a252b1cc9b2f2
