### ISSUE TITLE
Aborting fn install process leaves partially copied fn cli tool in target directory 

### ISSUE THREAD

**Issue by zootalures** [fnproject/cli#37]
```
curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh
If you are just upgrading your functions cli client, ignore this and wait a few seconds.
You may press Ctrl+C now to abort this process.

(wait for download to start) 
(hit Ctrl+C)

fn 
[1]    4299 bus error (core dumped)  fn
```

installer should download to a temp location and move over fn when complete

**Comment by treeder** [comment]
What do you think of removing that few second sleep?  I'm pretty sure most people will want the upgrade and this delay is just a waste for the most part. Is there any case where someone would run this installer and not want it upgraded? cc @rdallman

**Comment by rdallman** [comment]
seems fine to remove sleep, I can think of cases but it's not worth enumerating. at a minimum, we should just warn that we found a pre-existing install.

I think it's pretty standard to download to `/tmp` and move the file, we should do that anyway. (thanks for raising issue)
