### ISSUE TITLE
hope support go generate && go build

### ISSUE THREAD

**Issue by iwangxiaodong** [fnproject/cli#370]
hope support command "go generate"

**Comment by denismakogon** [comment]
Hi and welcome! Would you mind to explain in details what this issue is for?

**Comment by iwangxiaodong** [comment]
in https://github.com/fnproject/cli/blob/706f4031c48f9dc55b912a0845fe63bf1c170260/langs/go.go#L61

current：
    RUN cd /go/src/func/ && go build -o func

expected:
    RUN cd /go/src/func/ && go generate && go build -o func

ref -  https://blog.golang.org/generate

Thanks!

**Comment by iwangxiaodong** [comment]
@denismakogon 

Generate runs commands described by directives within existing
files. Those commands can run any process but the intent is to
create or update Go source files.

Go generate scans the file for directives, which are lines of
the form,

        //go:generate command argument...


ref -   https://golang.org/cmd/go/#hdr-Generate_Go_files_by_processing_source

**Comment by denismakogon** [comment]
Thanks. I do understand what `go generate` is for. However, any code generation has to be done prior `fn build` or `fn deploy`.

If you see this as a problem, you can write your own dockerfile and place it along `func.yml`, no need to change the CLI code.

**Comment by iwangxiaodong** [comment]
OK. I see.

Thank you!
