### ISSUE TITLE
[ux][feature] make "fn run" act similar to "docker run --rm" by default

### ISSUE THREAD

**Issue by denismakogon** [fnproject/cli#372]
At this particular moment, `fn run` becomes a source of filesystem pollution due to a number of untagged images being created with ever run iteration.

From UX and hard drive safeties, `fn run` must act as `docker run --rm`.
Reasons:
 - no FS pollution
 - `fn run` runs `docker build` every time.

**Comment by rikgibson** [comment]
`fn run` as it stands is going away - either it will be removed completely or it will be a thin wrapper over start/deploy/invoke/stop - so this should be closed I think.
