### ISSUE TITLE
`fn init` doesn't generate `schema_version` in `func.yaml` unless `--trigger` is specified.

### ISSUE THREAD

**Issue by rikgibson** [fnproject/cli#381]
```[~/test]: fn init --runtime go --trigger http bar6
Creating function at: /bar6
Runtime: go
Function boilerplate generated.
func.yaml created.
[~/test]: cat bar6/func.yaml
schema_version: 20180708
name: bar6
version: 0.0.1
runtime: go
entrypoint: ./func
format: json
triggers:
- name: bar6-trigger
  type: http
  source: /bar6-trigger
```

vs

```[~/test]: fn init --runtime go bar7
Creating function at: /bar7
Runtime: go
Function boilerplate generated.
func.yaml created.
[~/test]: cat bar7/func.yaml
name: bar7
version: 0.0.1
runtime: go
entrypoint: ./func
format: json```

**Comment by rikgibson** [comment]
I suspect this is to do with the CLI trying to determine whether a func.yaml is a v1 or v2 file - which should be based on the presence of schema-version rather than trigger - @JadeRedworth would know more on the wheres/whys of the code itself.

**Comment by mjg123** [comment]
Would be helpful if the issue text included the command you ran to get that output

**Comment by mjg123** [comment]
Actually, talking about this with @riconnon, this is intentional behaviour.

Unless a trigger is specified we generate a v1 func-file, and those have never had a schema version.

v1 func files will be dropped as part of removing routes in favour of triggers.

**Comment by mjg123** [comment]
Quoting @JadeRedworth:

This was intended, we are using schema_version to detect if func.yaml is V1 or V2, rather than identifying an actual version.
