### ISSUE TITLE
Remove old-style func.yaml generation from `fn init`

### ISSUE THREAD

**Issue by mjg123** [fnproject/cli#388]
This is mainly an exercise in cleaning up the codebase, but I would like to have `fn init` without any `--trigger` behave like `fn init --trigger none`.  This would let us remove a lot of duplicated code in init.go.

`run`, `deploy` etc are not affected, only `init`.

**Comment by rikgibson** [comment]
Yep, this is exactly what should happen - `--trigger none` was just a bridge to keep both worlds working during the V2 development.
