### ISSUE TITLE
fn invoke with java fdk helloworld gives 502 error 

### ISSUE THREAD

**Issue by sachin-pikle** [fnproject/cli#392]
I tried running a HelloWorld java using triggers and fn invoke... and I get a 502 in invoke.

fn init --runtime java --trigger http sac-java-t-fn

FN_REGISTRY=demouser fn -v deploy --app db-app --local --no-bump

curl http://localhost:8080/t/db-app/sac-java-t-fn-trigger

Curl works but I get a 502 error for Java helloworld fn invoke below:

fn invoke db-app sac-java-t-fn
{"message":"container exit code 2"}

Fn: Error calling function: status 502

See 'fn <command> --help' for more information. Client version: 0.4.150

**Comment by zootalures** [comment]
This is because the Java FDK is expecting FN_PATH and FN_REQUEST_URL to be set 
```
Required environment variable FN_PATH is not set - are you running a function outside of fn run?
```

**Comment by zootalures** [comment]
Invoke has changed the expected call contract and the Java FDK has not been updated to reflect that change.

**Comment by sachin-pikle** [comment]
Is this an easy fix?

**Comment by michael-w-williams** [comment]
More information after working on the node.js tutorial. Node.js is also giving me a 404 "Route not found" with `fn call`. The `fn invoke` command works fine. So taking the error message at face value I added a route: 

    fn create route nodeapp /nodefn fndemouser/nodefn:0.0.2

Now call works if you specify the content type. So `fn call` simply needs to look for a trigger rather than a route in the future.

**Comment by sachin-pikle** [comment]
Mike - Routes will be deprecated. 
Routes --> fn call

**Comment by gviedma** [comment]
Note that this issue originates on the server-side (not on the CLI), and it affects all FDKs. A fix is available on https://github.com/fnproject/fn/pull/1192
