### ISSUE TITLE
Fn deploy --all overwrites the trigger information in func.yaml files

### ISSUE THREAD

**Issue by peterj** [fnproject/cli#395]
Follow these instructions: 
```
# Create app.yaml that defines the app name
echo "name: greeter-app" > app.yaml
# Create a hello function in /hello subfolder
fn init --runtime go --trigger http hello
# Create a goodbye function in /goodbye subfolder
fn init --runtime go --trigger http goodbye
```

If you look at the `func.yaml` file under /hello and /goodbye folders, you will see the trigger information (expected).

Now, run `fn deploy --all` - deployment will finish and routes will be created (not triggers) and the func.yaml will not have the trigger information anymore.

**Comment by JadeRedworth** [comment]
Issue resolved by: [#404 Removes routes and migrates everything to V2 APIs](https://github.com/fnproject/cli/pull/404)
