### ISSUE TITLE
FN CLI 0.5.1 not working

### ISSUE THREAD

**Issue by itsmurugappan** [fnproject/cli#424]
i have pointed to the correct FN_API_URL.

I get the below error for all commands

Fn list functions {app name}

Fn: [GET /apps][404] ListApps default  &{Fields: Message:}

See 'fn <command> --help' for more information. Client version: 0.5.1

**Comment by rdallman** [comment]
getting this as well, thanks for raising... looking into it

**Comment by rdallman** [comment]
one thing to note, FN_API_URL must be `/v2` now... I am updating our defaults as well
