### ISSUE TITLE
Fn list calls doesn't work/return anything useful

### ISSUE THREAD

**Issue by peterj** [fnproject/cli#428]
Command and the output: 
```
$ fn list calls testapp1

Fn: function  not found

See 'fn <command> --help' for more information. Client version: 0.5.2
```

**Comment by rdallman** [comment]
listing calls is by function instead of app now (for better or worse), this api isn't log for this world fwiw...

**Comment by rdallman** [comment]
gonna close unless discussion is needed, feel free to re open
