### ISSUE TITLE
Cannot get logs for a function invocation

### ISSUE THREAD

**Issue by gviedma** [fnproject/cli#430]
I noticed a couple of issues with the CLI that prevent me from getting logs for a function. Since the fixes are all related, I'm filing as a single ticket for simplicity.

Version information:
```
$ fn version
Client version is latest version: 0.5.4
Server version:  0.3.566
```

1. fn logs help is incorrect:
Currently outputs `fn [global options] get logs <app-name> <call-id>` but should be `fn [global options] get logs <app-name> <function-name> <call-id>`

2. fn logs fails to render the log message:
`DEBUG=1 fn get logs go-flow go-flow 01CQV73V87NG8G00GZJ000000Y`
```
HTTP/1.1 200 OK
Content-Length: 447
Content-Type: application/json; charset=utf-8
Date: Thu, 20 Sep 2018 10:18:13 GMT

{"message":"Successfully loaded log","log":{"call_id":"01CQV73V87NG8G00GZJ000000Y","log":"header: Fnproject-Stageid true 2\nheader: Fnproject-Flowid true 471678d5-7be9-4e61-ac06-ee42224aa1c8\nAwakened flow 471678d5-7be9-4e61-ac06-ee42224aa1c8\nHandling continuation\nInvoking continuation with 1 args\nDecoding arg of type string\nDecoded datum of type *models.ModelBlobDatum\nWriting successful result foo\nConverting value to ModelBlobDatum\n"}}

Fn: json: cannot unmarshal object into Go struct field Log.log of type string
```

3. fn list calls help is incorrect:
Currently outputs `fn [global options] list calls [command options] <app-name>` but should be ` fn [global options] list calls [command options] <app-name> <function-name>`

The help message also includes references to routes which should be removed.

**Comment by JadeRedworth** [comment]
@gviedma @mantree This shouldn't be closed just yet, no. 1 and 3 still need to be changed in the CLI.

**Comment by gviedma** [comment]
Agreed
