### ISSUE TITLE
Show App , Function and Trigger IDs more prominantly in CLI 

### ISSUE THREAD

**Issue by zootalures** [fnproject/cli#449]
Fn list operations should include IDs in the tabluar responses  - these are necessary to do a bunch of operations since V2 

right now you need do do an inspect, then copy and paste from a JSON body

**Comment by denismakogon** [comment]
Should we just allow to dump out the JSON payload for `list` command? Or do both?

**Comment by delabassee** [comment]
What about adding support for human parsable alias for FunctionId?

**Comment by zootalures** [comment]
Right now I just want the IDs in list operations I think - aliasing is complex and I don't want to pollute the domain model yet - maybe later.

**Comment by zootalures** [comment]
i.e.  with v2 model we have operations that depend on users knowing IDs and they are hard to find now.
