### ISSUE TITLE
Creating a function does not default to "http-stream" format

### ISSUE THREAD

**Issue by JadeRedworth** [fnproject/cli#455]
When creating functions and not supplying a `--format` the CLI will fail with invalid format. The format should default to creating functions in the right format `http-stream`.
 
```
$ fn create func justin-app hello-world i386/hello-world:linux --memory=128 --timeout=120
Fn: Invalid format on Fn
See 'fn <command> --help' for more information. Client version: 0.5.15
```

**Comment by rikgibson** [comment]
Tested on latest CLI - 0.5.29 - against local Fn and remote Oracle Functions server and this is no longer an issue, so closing.
