### ISSUE TITLE
Fn cli "fn update app config" doesn't work

### ISSUE THREAD

**Issue by JadeRedworth** [fnproject/cli#462]
Updating an apps config with: `fn update app --config KEY=VALUE <app-name>` does not work. You can update the config with: `fn config app <app-name> KEY VALUE`.

**Comment by abhirockzz** [comment]
@JadeRedworth  The same issue applies to `syslog-url` as well i.e. if there is an existing value `fn update app --syslog-url=newvalue myapp` will not work. I guess the fix is as simple as `if len(c.String("syslog-url")) > 0`

**Comment by abhirockzz** [comment]
Filed an issue - https://github.com/fnproject/cli/issues/464

**Comment by JadeRedworth** [comment]
@abhirockzz ok I will include a fix in the same PR then!
