### ISSUE TITLE
"fn update app --syslog-url" does not work

### ISSUE THREAD

**Issue by abhirockzz** [fnproject/cli#464]
If there is an existing value for `syslog-url`,  `fn update app --syslog-url=newvalue myapp` will not work. I guess the fix is as simple as `if len(c.String("syslog-url")) > 0`

**Comment by rikgibson** [comment]
Fixed by #463

**Comment by rikgibson** [comment]
Fixed by #463

**Comment by rikgibson** [comment]
Fixed in #463
