### ISSUE TITLE
 connect: connection refused

### ISSUE THREAD

**Issue by cristicmf** [fnproject/cli#496]
Fn: Failed to update app config: Get http://localhost:7080/v2/apps?name=myapp2: dial tcp 127.0.0.1:7080: connect: connection refused

**Comment by zootalures** [comment]
Thanks for feedback, could you provide some more details about how you got to this error?

Also it looks like you are running fn on a custom port (7080) can you check that your fn server is running on that port by providing the output of ‘docker ps’ for the fnserver container

**Comment by zootalures** [comment]
closing
