### ISSUE TITLE
"build:" output elided

### ISSUE THREAD

**Issue by jan-g** [fnproject/cli#5]
The following func.yaml seems to have broken somewhere between 0.3.63 and 0.3.69:

```
name: fn-test/test-4
version: 0.0.1
runtime: java

path: /test
timeout: 450

build:
  - mvn package dependency:copy-dependencies -DincludeScope=runtime -DskipTests=true -Dmdep.prependGroupId=true -DoutputDirectory=target

cmd: com.fnproject.fn.integration.ExerciseEverything::handleRequest
```

specifically, the "build" commands are not run prior to packaging the content with a supplied Dockerfile. Is this accidental? This was pretty useful behaviour for runtimes like the Java one where it's often the case that a function may be a module of a larger project.

**Comment by jan-g** [comment]
(Specifically, 0.3.63 works; this is broken in 0.3.64 and onwards.)

**Comment by jan-g** [comment]
Actually - it's working, it's just not showing any output.

I'm fine(ish)* with this in the success case, but it's eating any diagnostics on failure.

* package managers and corporate proxies and hanging downloads are a thing that I'd rather the user got to see rather than sitting for n minutes with no feedback.

**Comment by treeder** [comment]
Is this still an issue?

**Comment by zootalures** [comment]
I don't think this should be swallowed on a verbose build
