### ISSUE TITLE
pagination of cli

### ISSUE THREAD

**Issue by rdallman** [fnproject/cli#50]
need to figure out what api we want for this. we could bake into cli just getting all results or add pagination parameters to cli commands. in any case, we're going to start showing just the first 30 results here pretty soon in the cli, and we seem to be pushing the cli on people, so should probably have something for lack of ui / other tools.

**Comment by treeder** [comment]
I at the very least (like you mentioned) have a --cursor flag, `fn x list --cursor c`. But could also stay open and page like `more`.  Or perhaps remember cursor in `~/.fn/somefile` then `fn x list --next`.

**Comment by carimura** [comment]
doh. 23 days old. let's make a decision cause right now can only get first 30.

any input @hibooboo2 @denismakogon @derekschultz ?

**Comment by denismakogon** [comment]
I'm on it. Swagger fixed, PRs for fn and fn_go are both ready. Once they would be merged, i'll jump on CLI.

**Comment by hibooboo2** [comment]
Ref the prs to this issue Please.

**Comment by denismakogon** [comment]
@hibooboo2 sure. There's one related - #77

**Comment by hibooboo2** [comment]
Thats an issue. I meant your prs.

**Comment by hibooboo2** [comment]
Ohh we do not have any pr's implementing this.
Nevermind

**Comment by treeder** [comment]
Libs updated to 0.2.1

**Comment by denismakogon** [comment]
well, it appeared that CLI still uses `funcy/functions_go` code, so it'll take some time to fix that in first place.
