### ISSUE TITLE
Windows CLI output has encoding issue and hard to read

### ISSUE THREAD

**Issue by tommysu** [fnproject/cli#500]
CLI version: 0.5.33
FN Server version: 0.3.630

The output of the cli contains characters that makes the text difficult to read.  This happens in both cmd and powershell.

<img width="632" alt="fncliencoding" src="https://user-images.githubusercontent.com/13800003/49602623-bd5b5200-f93d-11e8-8356-9505e3581c7a.PNG">

**Comment by harryjsmith** [comment]
Fixed by #566
