### ISSUE TITLE
Unsetting a config key that doesn't exist panics on nil config list

### ISSUE THREAD

**Issue by bencurrerburgess** [fnproject/cli#505]
Bug

**Steps to reproduce:**
1. Create a new app and a new function within that app
2. Unset any config key (one that does not exist) on the new function
`fn unset config function <app-name> <function-name> anykey`

This will panic on assignment entry to a nil map.

The same issue will occur on an app config:
1. create a new app
2. unset any config key on the new app
`fn unset config app <app-name> anykey`

The map in question that is nil is the fn.config

**Comment by rikgibson** [comment]
PRs welcome @bencurrerburgess...

**Comment by bencurrerburgess** [comment]
Issue fixed in PR: #508

**Comment by bencurrerburgess** [comment]
Issue fixed in PR: #508
