### ISSUE TITLE
Inconsistent errors with bad input

### ISSUE THREAD

**Issue by bencurrerburgess** [fnproject/cli#506]
With the given command the error messages returned are inconsistent / incorrect:

### Correct error message
`fn get logs <non-existant-app-name> <non-existant-function-name> <non-existsant-call-id>`
returns a correctly formatted message:
`fn app <non-existant-app-name> not found`

### No error message
`fn get logs <real-app-name> <non-existant-function-name> <non-existsant-call-id>`
returns siltently, no complaint and no output

### Incorrect error message
`fn get logs <real-app-name> <real-function-name> <non-existsant-call-id>`
returns
`Fn: &{ } (*modelsv2.Error) is not supported by the TextConsumer, can be resolved by supporting TextUnmarshaler interface`

Suspected that this may have been introduced by #404

**Comment by zootalures** [comment]
closing as we've removed logs
