### ISSUE TITLE
DOC: update CLI README.md

### ISSUE THREAD

**Issue by delabassee** [fnproject/cli#539]
The CLI readme is outdated, ex. it still mentions `call`, `test` but it doesn't mention `invoke` nor `migrate`.

It needs to be updated :
* we could cut'n paste the `fn --help` output (and keep it up-to-date ;-) )
* or we could greatly simplify it and suggest to use `fn --help` as the source of truth (my personal choice)

**Comment by delabassee** [comment]
cc @carimura

**Comment by michael-w-williams** [comment]
Updated the readme. Removed old stuff and linked to CLI Reference. See: https://github.com/fnproject/cli/pull/540

**Comment by michael-w-williams** [comment]
Merged see: https://github.com/fnproject/cli/pull/540
