### ISSUE TITLE
Add "invoke endpoint" command feature

### ISSUE THREAD

**Issue by denismakogon** [fnproject/cli#546]
As a user, I'd like to get annotation URL like fn invoke blah blah `--invoke-annotation-only` (don't blame me, haven't thought about better option) or anything that might be better to get an invoke annotation, so, I can wire that to OCI cURL.

In order to fit CLI framework there's a chance to add requested feature to a set of "get" commands:
```
fn inspect fn <app> <fn> --invoke-endpoint-only
```
or
```
fn get invoke-endpoint <app> <fn>
```
or
```
fn get annotation <app> <fn>
```
or whatever can be useful.

**Comment by abhirockzz** [comment]
Have you tried `fn inspect fn --endpoint <app-name> <fn-name>` ?

**Comment by denismakogon** [comment]
Okay, haven't seen that, thanks.
