### ISSUE TITLE
[FDK-Go][Boilerplate] Go Mod VS Go Dep

### ISSUE THREAD

**Issue by denismakogon** [fnproject/cli#548]
In almost all Go projects we've done so far we migrated from `go dep` to `go mod`.
But what about FDK GO and the boilerplate we generate for Go functions?

**Comment by rdallman** [comment]
same thing, we should move everything to mod

**Comment by rdallman** [comment]
if users want to use dep, they can still do that, but for our generated stuff and for the fdk-go itself it should all be mod

**Comment by zootalures** [comment]
This appears to be done , fn init --runtime go produces mod now. , closing
