### ISSUE TITLE
CLI on windows emits unix terminal control chars in windows, makes output look bad 

### ISSUE THREAD

**Issue by zootalures** [fnproject/cli#561]
The term coloring in CLI does not appear to correctly switch itself off on windows (see below) 

this looks bad 

![image](https://user-images.githubusercontent.com/4050521/55290222-68e65180-53c8-11e9-8c41-011066c80b20.png)

**Comment by Daniel15** [comment]
For what it's worth, it works in Cmder and in VS Code's terminal for me, just not in the regular Windows terminal.
