### ISSUE TITLE
Command line arguments should take precedence over func.yaml

### ISSUE THREAD

**Issue by carimura** [fnproject/cli#67]
```
❯ docker images | grep carimura/hello
carimura/hello                0.0.1               2876e9c5befb        3 days ago          6.98MB
carimura/hello                0.0.2               05a3bd381fc2        3 weeks ago         1.84kB
carimura/hello                0.0.3               05a3bd381fc2        3 weeks ago         1.84kB

~/workspace/hello
❯ fn routes l myapp
path    image            endpoint
/hello    carimura/hello:0.0.3    localhost:8080/r/myapp/hello

~/workspace/hello
❯ fn routes u myapp hello -i carimura/hello:0.0.2
myapp /hello updated

~/workspace/hello
❯ fn routes l myapp
path    image            endpoint
/hello    carimura/hello:0.0.3    localhost:8080/r/myapp/hello
```

**Comment by denismakogon** [comment]
Have you tried —ignore-fn-file? (I’m out right now, can’t test it)

**Comment by carimura** [comment]
right, that worked. was that the solution to arguments vs yaml precedence conversation from a few months ago? maybe a notification in the response would be useful to let the user know the yaml file is taking precedence, "did you mean to use --ignore-fn-file" or something....

**Comment by denismakogon** [comment]
That flag was brought to CLI yo let people update routes without having func file around. So, yeah it was an independent fix that appeared to be a solution for that discussion.

**Comment by carimura** [comment]
k thanks makes sense. i still think that it's confusing when the func file does exist and it takes precedence in this situation when it does NOT take precedence in other situations (ie setting config... CLI takes precedence here, not func file)

**Comment by denismakogon** [comment]
If func file does not exist CLI would fail with corresponding error.

**Comment by treeder** [comment]
Update CLI, it doesn't even look at func.yaml file anymore.

**Comment by carimura** [comment]
Ah ok updating to all latest.
