### ISSUE TITLE
how to change the port(8080) of the Fn Server when execute fn start?

### ISSUE THREAD

**Issue by xhusky** [fnproject/cli#68]
The default port is `8080`, how to change the port of Fn Server when execute `fn start`, thanks.

**Comment by rdallman** [comment]
can't atm https://github.com/fnproject/cli/blob/master/start.go#L47 but PRs welcome :)

**Comment by xhusky** [comment]
got it, thanks @rdallman

**Comment by treeder** [comment]
Did you mean to close this?

**Comment by xhusky** [comment]
Yes, It's not necessary for me. but someone maybe need it. Reopen this? I am a golang beginner, I will read source code of this cli firstly.

**Comment by peeyushsrj** [comment]
I think this might help https://github.com/fnproject/fn/blob/master/docs/operating/options.md
