### ISSUE TITLE
fn --help USAGE section contains broken link

### ISSUE THREAD

**Issue by r4zzz4k** [fnproject/cli#78]
```sh
> fn --help
fn 0.4.11

Fn command line tool

USAGE:
   Check the docs at https://github.com/fnproject/fn/blob/master/fn/README.md

ENVIRONMENT VARIABLES:
...
```
The link to [README.md](https://github.com/fnproject/fn/blob/master/fn/README.md) is broken.
Of course the CLI itself provides enough information to actually get started anyway, so it's probably just a cosmetic issue.

**Comment by treeder** [comment]
This has been fixed.
