### ISSUE TITLE
Make certain runtimes  hot by default

### ISSUE THREAD

**Issue by zootalures** [fnproject/cli#85]
Initially Java . 

```
fn init --runtime java 
cat func.yaml
...
format: http
...
```

**Comment by treeder** [comment]
Should we keep this open for all the other runtimes that have FDKs?

**Comment by zootalures** [comment]
Could do but IIRC they all need a fair bit of work to get to the point which lets this be switched on (including in cli) on init (assuming we want fn init -> fn run   to work without modification).
