### ISSUE TITLE
When creating a route, specifying an image and a tag appears to be mandatory

### ISSUE THREAD

**Issue by nigeldeakin** [fnproject/cli#96]
I'm trying to create a route using the command `fn routes create hello-async-app hello1` 

However this gives the message `ERROR: no image specified`. 

If I type `fn routes create --help`, the `--image` parameter is described as an "option", which implies it is optional. Is it now always mandatory? If so should the online help say this?

If I specify an image name (as given in the example at https://github.com/fnproject/fn/blob/master/docs/definitions.md):
```
fn routes create myapp /path --config k1=v1 --config k2=v2 --image fnproject/hello
```
This fails with 
```
ERROR: image name must have a tag
```

**Comment by denismakogon** [comment]
Tag is mandatory for images, this is very least requirement for function versioning.

**Comment by nigeldeakin** [comment]
Note I get  `ERROR: no image specified` even if there is a `func.yml` in the same directory which specifies the image.

**Comment by treeder** [comment]
We stopped picking up the func.yaml for any functionality that maps directly to API calls (#75), now only run and deploy will use func.yaml's .

That definitions.md probably needs updating (or delete the commands it has).
